### ISSUE TITLE
Convert boc result to transaction hash

### ISSUE THREAD

**Issue by 0xvictorb** [tonwhales/wallet#1003]
### Bug Type

Other

### Reproduction steps

Hi, I don’t think this is a bug but actually a technical question. I’m trying to convert the BOC result to a transaction hash, but somehow it doesn’t work on Tonhub, while the same action works with TONkeeper wallet. Below are the steps to reproduce:

1. Connect Tonhub to https://app.tonpad.space
2. Do a swap transaction at [link](https://app.tonpad.space/ton-fun/0:a09e02455c4ef9d22023b17c53a1e946a8943c96cd9c8e2d5efdea3319b06361)
3. Get the boc result and convert to transaction hash, like below:
```typescript
const bocCell = Cell.fromBase64(bocResult) // bocResult return from Wallet
const txHash = bocCell.hash().toString('hex')
 console.log(txHash)
 ```
 4. Notice transaction hash and check on tonviewer.com

### Actual result

Invalid transaction hash

### Expected result

Valid transaction hash

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: iPhone 13 Pro Max
- OS: 
- Browser: Tonhub App
- Version: 2.3.8 (742)

**Comment by natsoe7** [comment]
Hi
