### ISSUE TITLE
Get wallet address after offline creation

### ISSUE THREAD

**Issue by i0xHeX** [tonwhales/wallet#153]
This feature will allow us to create so called "cold" wallets without using external tools like hardware wallets. Currently it's impossible to get wallet address created offline without actually connecting to the internet:
![image](https://user-images.githubusercontent.com/33582973/171229165-4550d955-5973-449d-a5e5-8078191a8c5d.png)

**Comment by ex3ndr** [comment]
Hello! If you want to have extra security you can use our [ton-cli](https://github.com/tonwhales/ton-cli) that have an ability to work completely offline and can even send transactions. Just apply `--offline` to it's arguments when starting.

Also you can connect `ton-cli` to our [Ledger App](https://github.com/ton-foundation/ledger-app-ton). Currently only Nano S+ supported.
