### ISSUE TITLE
Try to use 'bin' argument for sign transaction to my own contract with custom payload

### ISSUE THREAD

**Issue by vplotvinov** [tonwhales/wallet#239]
Hello! I tried to use transaction like https://tonhub.com/transfer/${address}?amount=${amount}&bin=${payload}

How I generated payload:
```
beginCell()
  .storeUint(777, 32)
  .storeDict(someDictAsCell)
  .storeRef(someRefAsCell)
  .endCell()
  .toBoc() // or with idx: false. Same result
  .toString('base64')
  
```
  **What I did**
  When I try to use it via Sandbox wallet (with test.tonhub.com) it's looks like everything is fine. I saw popup with message info and can tap on send button but sandbox environment didn't see my testnet ton coins I guess it's another network.
  
 I decided to try it on mainnet with Tonhub wallet (ios version) and real coins but when I open link nothing happened. No error messages, just nothing. (_I used same link like for Sandbox but without 'test.'_)
 
 **Question**
 I wanna ask, have it is implemented on mainnet wallet (ios/android) and can I use it for sign my custom payload in transactions or I should use another way for to do this? If it's not implemented do you have some plans and estimates for doing it? 
 
 
 _p.s. Sorry, if it's wrong place for asking about it. I didn't find any tech channels for questions to whales._

**Comment by vzhovnitsky** [comment]
You can read more amount transfer links here https://developers.tonhub.com/docs/transfer-link
