### ISSUE TITLE
iOS: don't display jettons in tab with invoice and on main page

### ISSUE THREAD

**Issue by maxuver** [tonwhales/wallet#254]
**Bug Type**

UX

**Reproduction steps**

1. See Red Coin jetton invoice in Tonkeeper. Red Coin is here
2. Copy and paste wallet adresses from TonHub and Tonkeeper (proof that the same wallet) 
3. See Red Coin jetton invoice in TonHub. Red Coin missing 

https://user-images.githubusercontent.com/78837452/190851246-c063a823-50f3-4f1d-a823-513d8ed02f51.mp4

**Actual result**

Red Coin missing

**Expected result**

Red Coin is here

**Suggested Severity**

Medium

**Device**

Device: Apple iPhone 11
OS: iOS 15.6.1
App Version 1.19.7

**Additional Context**

No response

**Comment by vzhovnitsky** [comment]
The issue is not in bad UX, there was a bug in our back end. It has been fixed for some time now.
