### ISSUE TITLE
`MAX` Button in Staking Section Doesn't Work Correctly

### ISSUE THREAD

**Issue by datonawy** [tonwhales/wallet#255]
### Bug Type

UX

### Reproduction steps

1- In an account with zero balance (brand new) go to staking extension.
2- Select any staking pool.
3- Press `MAX` button on the top right.

### Actual result

The APP chooses a staking balance of `-0.2` instead of `0`.
![image](https://user-images.githubusercontent.com/94648660/190870839-f7960341-4e68-4bf8-b5e4-722875e8cd69.png)

### Expected result

The APP should select `0` or fire a prompt that the account is balance-less.

### Suggested Severity

Low

### Device

Smartphone (please complete the following information):
- Device: Redmi Note 7
- OS: Android 12
- Version 1.19.7

**Comment by vzhovnitsky** [comment]
Fixed in v2.0.0
