### ISSUE TITLE
SPAM filter works only for transactions with a comment

### ISSUE THREAD

**Issue by julialips** [tonwhales/wallet#259]
### Bug Type

Functional

### Reproduction steps

1. Open Tonhub app 
2. Log in to your wallet with positive balance
3. Go to Settings
4. Open SPAM filter feature and set the 'Min TON amount' = 10, click 'Apply' button and confirm the action in pop-up. 
5. Make send transaction less than 10 TON, with some comment, to another wallet. Pay attention for the list of transactions. 
     Actual result: The transaction is displayed in history with SPAM mark
6. Make send transaction less than 10 TON, without any comment, to another wallet. Pay attention for the list of transactions. 

### Actual result
The transaction is displayed in history without SPAM mark
<img width="253" alt="1234" src="https://user-images.githubusercontent.com/45575431/191255595-ad8de029-a127-4003-91f1-0903512a8da9.png">

### Expected result
The transaction is displayed in history with SPAM mark

### Suggested Severity

High

### Device

- Device: iPhone 11
- OS: 14.3

**Comment by vzhovnitsky** [comment]
Only transaction with comment would be a spam one (as you would spam to gain some attention to the message you are trying to deliver), you can always add that exact address to you deny-list, and it will be marked as spam.
