### ISSUE TITLE
iOS: Impossible to paste recovery phrases from a clipboard on the 'Import existing wallet' screen

### ISSUE THREAD

**Issue by julialips** [tonwhales/wallet#260]
### Bug Type

UX

### Reproduction steps

1. Open Tonhub
2. Click 'Import existing wallet' 
3. Copy phrases "forum plug observe jealous beach brave two improve imitate apology pen dwarf fade dream crop play drum stuff metal winner icon shuffle inner calm" and paste

### Actual result

Phrase is pasted into one line. Impossible to pass the flow fast, a little inconvenient every time to write it manually

https://user-images.githubusercontent.com/45575431/191318200-59df9d69-01e5-4c04-b063-f5cfed24a2b4.MP4

### Expected result
Phrase is parsed for words and each of them pasted into fields

### Suggested Severity

Medium

### Device

- Device: iPhone 11
- OS: 14.3

### Additional Context

The same behavior is tested on Tonkeeper and it works as expected.

**Comment by vzhovnitsky** [comment]
Copying your seed-phrase to clipboard is not secure. Yet we added that feature for advanced users.
