### ISSUE TITLE
Staking. Unstake with 0 amount is possible and blockchain eat commission (iOS)

### ISSUE THREAD

**Issue by d1markov** [tonwhales/wallet#261]
TonHub v1.19.7
Iphone 11 iOS 15.3.1

Steps:
1. Go to Staking
2. Tap on first pool
3. Tap on "Unstake"
4. Enter 0 amount
5. Tap On "Continue"

Actual Result:
Main screen opened
Balance decreased due to commissions
In operations list i got 2 operations -0.2 and +0.09 but really, I lost my money =(

Expected result:
errror "...you don't have enougth coins staked"
withdrawal request screen still open

https://user-images.githubusercontent.com/40431429/191360865-7861559a-4dee-42bc-8e84-0cc33def63c0.mp4

**Comment by vzhovnitsky** [comment]
Sending 0 (actually 0,2 - withdraw comission ) sends a command to withdraw ALL funds that are staked.
