### ISSUE TITLE
Tonhub cannot select from contacts while sending jettons

### ISSUE THREAD

**Issue by ekrotoken** [tonwhales/wallet#328]
### Bug Type

Functional

### Reproduction steps

When sending jettons from a jetton account the receiver cannot be chosen from the contacts.

### Actual result

The contacts allow for sending TONs only.

### Expected result

When sending using Contacts the expected behavior is either
1. to choose from the token-acount list (currency, e.g. TON, Jetton1, Jetton2, ...), or
2. to send from any account (basic TON or a jettons's) providing Contact list to choose recipient from

### Suggested Severity

High

### Device

Android

**Comment by vzhovnitsky** [comment]
Thanks for the issue, we will try to make some changes to account for that!

**Comment by vzhovnitsky** [comment]
We have a new update coming up which will allow you choosing from contacts and recent transactions.
