### ISSUE TITLE
Unable to transfer funds via domain address

### ISSUE THREAD

**Issue by reveloper** [tonwhales/wallet#358]
### Bug Type

Functional

### Reproduction steps

1. Open the _transfer_ window in Tonhub
1. Input valid .ton / .t.me domain address
2. Click the _continue_ button.

### Actual result

Got the error "Invalid domain"

### Expected result

Successful sending funds

### Suggested Severity

Medium

### Device

Smartphone (please complete the following information):
- Device: iPhone 12
- OS: 16.3.1
- Tonhub:  v.1.24.0

### Additional Context

Video

https://user-images.githubusercontent.com/39581753/223047116-d763190d-3b24-4012-93ff-889bc61e3a8f.MP4

**Comment by vzhovnitsky** [comment]
Should be fixed with our latest update.
