### ISSUE TITLE
Support for sending coins from any version of the wallet contract 

### ISSUE THREAD

**Issue by mr-abramenko** [tonwhales/wallet#50]
Thank you for your work on the wallet! Cool!
It would be great if you added the ability to choose from which version of the wallet contract (for example, v3 or v4, i.e. from which address) the tones will be sent.
An example of a situation where this is necessary: I staked a coin with v3 using the nominator’s contract, the wallet application has been updated to v4, but in order to withdraw coins from the nominator’s contract, you need to send a withdrawal request from the v3 wallet.

**Comment by ex3ndr** [comment]
Hello! We recommend to use old wallet and withdraw from nominator's contract and deposit from a new one, but we will evaluate is it is possible to use legacy wallets.

**Comment by mr-abramenko** [comment]
Thank you!
